name: Typst Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Typst
        run: |
          wget https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar xf *.tar.xz
          echo "$(pwd)/typst-x86_64-unknown-linux-musl/" >> $GITHUB_PATH
      - name: Compile report with Typst
        run: chmod +x compile.sh && ./compile.sh
      - name: Upload report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: report.pdf
